services:
  api_gateway:
    build:  ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3000

  users_microservice:
    build:  ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: pnpm run start:dev

  car_microservice:
    build:  ./car-microservice
    volumes:
      - ./car-microservice/src:/usr/src/app/src
    depends_on:
      - mysql_db  # Ensure the MySQL database is running
    command: sh -c "/wait-for-it.sh mysql_db:3306 --strict --timeout=300 && pnpm run start:dev"  # Run TypeORM migrations and seed script

  nats:
    image: nats
    ports:
      - 4222:4222

  mysql_db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  