services:
  api_gateway:
    build:  ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: pnpm run start
    environment:
      - PORT=3000

  users_microservice:
    build:  ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: pnpm run start

  car_microservice:
    build:  ./car-microservice
    volumes:
      - ./car-microservice/src:/usr/src/app/src
    command: pnpm run start

  nats:
    image: nats
    ports:
      - 4222:4222

  mysql_db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  