services:
  api_gateway:
    build:  ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: pnpm run start:dev
    environment:
      - PORT=3000

  users_microservice:
    build:  ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
  
  nats:
    image: nats
    ports:
      - 4222:4222
  